# site settings
title: Stephenson Scholarship Hall
subtitle: at the University of Kansas
email: stephensonscholhall52@gmail.com
description: Cat ipsum dolor sit amet, damn that dog human is washing you why halp oh the horror flee scratch hiss bite. Put toy mouse in food bowl run out of litter box at full speed 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1404 Alumni Place Drive
city: Lawrence
state: KS
zip_code: 66044
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/groups/stephensonhall2017l18/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/StephensonKU

# build settings
markdown: kramdown

sass:
  style: compressed
